celery_django/django_back/django_back/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

celery_django/django_back/main/urls.py
from django.urls import path

from . import views

app_name = 'djangoServer'
urlpatterns = [
    path('', views.session_list, name='session_list'),
    path('create_session_form', views.create_session_form, name='create_session_form'),
    path('create_session', views.submit_create_session, name='submit_create_session'),
    path('session/<int:session_id>', views.session_view, name='session-view'),
    path('iteration/<int:iteration_id>', views.iteration_view, name='iteration_view'),
    path('review_iteration/<int:session_id>/<int:iteration_id>', views.submit_iteration_review, name='submit_iteration_review'),
    path('clear', views.clear, name='clear'),
]

celery_django/django_back/main/models.py
from datetime import datetime
from enum import Enum

from django.db import models


class IterationStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    IN_PROGRESS = 'IN_PROGRESS'
    FINISHED = 'FINISHED'
    REVIEWED = 'REVIEWED'


class Session(models.Model):
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=datetime.now)


class Iteration(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    prev = models.ForeignKey("self", on_delete=models.SET_NULL, blank=True, null=True)
    status = models.CharField(max_length=32,
                              choices=[(tag, tag.value) for tag in IterationStatus],
                              default=IterationStatus.NOT_STARTED)
    created_date = models.DateTimeField(default=datetime.now)
    input_value = models.OneToOneField('Sentence', on_delete=models.SET_NULL, primary_key=False,
                                       related_name='input_for',
                                       blank=True, null=True)


class Group(models.Model):
    iteration = models.ForeignKey(Iteration, on_delete=models.CASCADE)
    suitable = models.BooleanField(default=None, blank=True, null=True)


class Sentence(models.Model):
    count = models.IntegerField(default=0)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    important_words = models.TextField()
    tree = models.BinaryField(null=True, blank=True)

celery_django/django_back/main/views.py
from typing import List

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from main.models import Session, Iteration, IterationStatus
from main.service import session_service


# TODO: transactional
def session_list(request):
    sessions: List[Session] = session_service.get_sessions()

    session_list_view = [{'id': session.id, 'title': session.title} for session in list(sessions)]
    context = {
        'sessions_list': session_list_view,
    }
    return render(request, 'session_list.html', context=context)


def create_session_form(request):
    return render(request, 'start_session.html')


# TODO: transactional
def submit_create_session(request):
    sentence_text = request.POST['sentence']

    session = session_service.start_new_session(sentence_text)
    return HttpResponseRedirect("/session/" + str(session.id))


# TODO: transactional
def session_view(request, session_id):
    session = get_object_or_404(Session, pk=session_id)
    iterations = Iteration.objects.all().filter(session=session).order_by('-created_date').all()

    reviewed_list = []
    not_reviewed_list = []
    for iteration in iterations:
        obj = {
            'text': iteration.input_value.text,
            'id': iteration.id,
            'date': iteration.created_date,
        }
        if iteration.status == str(IterationStatus.REVIEWED):
            reviewed_list.append(obj)
        else:
            not_reviewed_list.append(obj)
    context = {
        'iterations_reviewed': reviewed_list,
        'iterations_not_reviewed': not_reviewed_list,
        'session_id': session_id,
        'session_name': session.title,
    }
    return render(request, 'iterations_list.html', context=context)


# TODO: transactional
def iteration_view(request, iteration_id):
    iteration = get_object_or_404(Iteration, pk=iteration_id)

    if iteration.status == str(IterationStatus.NOT_STARTED):
        return HttpResponse("Still not started")
    if iteration.status == str(IterationStatus.IN_PROGRESS):
        return HttpResponse("Still in progress")
    if iteration.status == str(IterationStatus.REVIEWED):
        return HttpResponse("Already reviewed")

    groups_list_view = []

    for group in iteration.group_set.all():
        groups_list_view.append({
            'sentences': [
                {
                    'text': sent.text,
                    'preview': "count: " + str(sent.count) + "; important words: " + sent.important_words
                }
                for sent in list(group.sentence_set.order_by('-count').all())],
            'id': group.id
        })

    context = {
        'groups_list': groups_list_view,
        'session_id': iteration.session_id,
        'iteration_id': iteration.id,
        'input_text': iteration.input_value.important_words,
    }
    return render(request, 'iteration.html', context=context)


# TODO: transactional
def submit_iteration_review(request, session_id, iteration_id):
    group_ids_list: List[int] = []
    for field in request.POST:
        prefix = "group"
        field_text: str = field
        if field_text.startswith(prefix):
            group_id = int(field_text[len(prefix):len(field_text)])
            group_ids_list.append(group_id)

    session_service.review_iteration(session_id, iteration_id, group_ids_list)
    return HttpResponseRedirect("/session/" + str(session_id))


# TODO: transactional
def clear(request):
    session_service.clear_db()
    return HttpResponse('Done')

celery_django/django_back/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% block title %}<title>Tongue</title>{% endblock %}
</head>
<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

celery_django/django_back/templates/iteration.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Input words: {{ input_text }}</h1>
    <form action="{% url 'djangoServer:submit_iteration_review' session_id iteration_id %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if groups_list %}
                {% for group in groups_list %}
                    <input type="checkbox" name="group{{ group.id }}" id="group{{ group.id }}"
                           value="{{ group.id }}">
                    {#                        <label for="group{{ group.id }}">{{ group.id }}</label>#}
                    <details open>
                        <summary>{{ group.id }}</summary>
                        {% for sentence in group.sentences %}
                            <details>
                                <summary>{{ sentence.preview }}</summary>
                                {{ sentence.text }}
                            </details>
                        {% endfor %}
                    </details>
                    <hr>
                {% endfor %}
            {% else %}
                <p>There is no group</p>
            {% endif %}
        </fieldset>
        <input type="submit" value="Start iteration">
    </form>
{% endblock %}

celery_django/django_back/templates/iterations_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Session: {{ session_name }}</h1>
    {% if iterations_not_reviewed %}
        <h3>Not reviewed:</h3>
        <ul>
            {% for iteration in iterations_not_reviewed %}
                <li><a href="/iteration/{{ iteration.id }}">{{ iteration.id }} {{ iteration.date }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if iterations_reviewed %}
        <h3>Reviewed:</h3>
        <ul>
            {% for iteration in iterations_reviewed %}
                <li><a href="/iteration/{{ iteration.id }}">{{ iteration.id }} {{ iteration.date }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

celery_django/django_back/templates/session_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Session list:</h1>
    {% if sessions_list %}
        <ul>
            {% for session in sessions_list %}
                <li><a href="/session/{{ session.id }}">{{ session.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no sessions</p>
    {% endif %}
    <a href="{% url 'djangoServer:create_session_form' %}">Create session</a>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'djangoServer:clear' %}">Clear database</a>
{% endblock %}

celery_django/django_back/templates/start_session.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Start session</h1>
    <form action="{% url 'djangoServer:submit_create_session' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Word</legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label>
                <input type="text" name="sentence">
            </label>
        </fieldset>
        <input type="submit" value="Create">
    </form>
{% endblock %}